# Generated by Django 3.2.5 on 2021-07-28 06:12

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ct', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_slug', models.SlugField(blank=True, max_length=355, null=True, unique=True)),
                ('about', models.CharField(max_length=500)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('status', models.CharField(choices=[('D', 'Draft'), ('F', 'Featured'), ('P', 'Project'), ('PB', 'Published'), ('PR', 'Private')], default='D', max_length=2)),
                ('keywords', models.TextField()),
                ('thumbnail', imagekit.models.fields.ProcessedImageField(upload_to='blogs')),
                ('date_added', models.DateField(auto_now_add=True)),
                ('last_edited', models.DateField()),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blogs.category')),
            ],
        ),
    ]
