# Generated by Django 3.2.5 on 2021-07-25 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='about',
            field=models.CharField(default='saddddddddddddd', max_length=500),
            preserve_default=False,
        ),
    ]
