# Generated by Django 3.2.5 on 2021-07-24 16:06

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to='blogs')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_img', to='products.item')),
            ],
            options={
                'verbose_name': 'Item image',
                'verbose_name_plural': 'Item images',
            },
        ),
    ]
