# Generated by Django 3.2.5 on 2021-07-24 16:19

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_itemimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemimage',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='items'),
        ),
    ]
