# Generated by Django 3.2.5 on 2021-07-25 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_itemimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('D', 'Draft'), ('F', 'Featured'), ('IS', 'In Stock'), ('NA', 'Not Available'), ('OS', 'Out Of Stock')], max_length=2),
        ),
    ]
